buffer_seek(network.send_buffer,buffer_seek_start,0)
buffer_write(network.send_buffer,buffer_u8,10)
buffer_write(network.send_buffer,buffer_u32,network.ID)
buffer_write(network.send_buffer,buffer_u32,key_right)
buffer_write(network.send_buffer,buffer_u32,key_left)
buffer_write(network.send_buffer,buffer_u32,key_up)
buffer_write(network.send_buffer,buffer_u32,key_down)
buffer_write(network.send_buffer,buffer_u32,horizontal_input)
buffer_write(network.send_buffer,buffer_u32,vertical_input)
buffer_write(network.send_buffer,buffer_u32,mouse_left_pressed)
buffer_write(network.send_buffer,buffer_u32,cursor_x)
buffer_write(network.send_buffer,buffer_u32,cursor_y)
network_send_udp(network.socket,network.ip,network.port,network.send_buffer,buffer_tell(network.send_buffer))
show_debug_message("network sent mid10")	
